### ISSUE TITLE
Add more utility slots

### ISSUE THREAD

**Issue by natmcconnell21** [johnthagen/stardust-rpg#1]
I would like to propose the addition of several utility equipment slots, so I can carry a pickaxe and a bugle at the same time for all of my mining, bugling needs.

**Comment by johnthagen** [comment]
There is a subtle game-play question we need to answer here: how many utility items should be able to be **equipped** at once?

I have a separate enhancement planned to add a generic inventory where extra equipment can be stored, but would not affect the character stats.  For example, the Candle adds `+1VIS`.  It seems reasonable to be able to equip the Candle and, say, the pickaxe at once.  But also, it could just be in your inventory, and we could just not make rules about the character having to "equip" it.

The old sheet had 3 equipable utility slots.

Thoughts?

**Comment by MutantSoldier** [comment]
I'm always about simplicity, which in this case means having all the macros ready to go and synced. There could be 10 slots for all I care. If that's in the form of an inventory, great. Just as long as it doesn't slow things down. I think we can all agree that multiple utility items is not the same wide as multiple weapons, shields, etc. They cost their gp and min Int, don't think there's a need for opportunity cost.

**Comment by drhagen** [comment]
There are really two question to ask about each utility item: does it impact combat and does it have a macro? If it affects combat, then it needs to be equipped whether it has a macro or not, otherwise you could have unlimited buffs. If it has a macro, then the item needs only to be in inventory. There is nothing necessarily wrong with having the macro available only when equipped, but this is a pain for items mainly useful out of combat.

But really utility items that affect combat should go into a weapon or shield slot. I mean, you can't effectively benefit from a candle while also wielding a sword and shield. I propose eliminating the utility slot and making the utility macros of items in inventory available at all times.

**Comment by johnthagen** [comment]
@drhagen 

> does it impact combat 

Currently only the light enabling Utility items (Candle, Torch, etc) have an effect on combat as they add {{VIS}}.  I thought that was a neat thing to do balance wise (incentive {{INT}} in order to get a little {{VIS}}), but I think you are right in that really it doesn't make sense to have a torch and a sword and shield "equipped" at once.

> and does it have a macro?

I will say that every Utility item I have conceived of has a macro, if nothing else just to speed up the game and give the player a button to push.  Also Utility macros have historically always rolled an {{APT}} check, which I think is good to quickly allow the DM to resolve either formally or informally how well the character did.

> I propose eliminating the utility slot and making the utility macros of items in inventory available at all times.

Looking at the bare items that currently exist (things that aren't utility): http://ec2-52-207-244-42.compute-1.amazonaws.com/sheet/items/

Those all really could just be utility items.  The only difference is those have been historically more "consumable" (though not sure how much game impact that it really had).

I am proposing:

1. Utility items no long are "equipped" in the sense they can increase your stats.  We have plenty of slots for that.  "Candles" and such are going to be just "light and throw" type things.
2. The existing bare items are converted to Utility items.
3. Add 4 more Utility slots (total of 5).

Question:
4. How to deal with "consumable" Utility items. Add a "quantity" for each Utility slot?  Convert the items like lock picks and disguise kits to non-consumable?

**Comment by johnthagen** [comment]
Merging into #5.
